(deftheme custom-tr-eclipse
  "Created 2015-04-19.")

(custom-theme-set-faces
 'custom-tr-eclipse
 '(default ((t (:family "Menlo" :foundry "nil" :width normal :height 140 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "black" :background "white" :stipple nil :inherit nil))))
 '(cursor ((t (:background "HotPink"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((t (:family "Sans Serif"))))
 '(escape-glyph ((t (:foreground "cyan4"))))
 '(minibuffer-prompt ((t (:foreground "medium blue"))))
 '(highlight ((t (:background "darkseagreen2"))))
 '(region ((t (:background "snow3"))))
 '(shadow ((t (:foreground "grey70"))))
 '(secondary-selection ((t (:background "paleturquoise"))))
 '(trailing-whitespace ((((class color) (background light)) (:background "red1")) (((class color) (background dark)) (:background "red1")) (t (:inverse-video t))))
 '(font-lock-builtin-face ((t (:foreground "black"))))
 '(font-lock-comment-delimiter-face ((default (:inherit (font-lock-comment-face)))))
 '(font-lock-comment-face ((t (:slant italic :foreground "ForestGreen"))))
 '(font-lock-constant-face ((t (:foreground "CadetBlue"))))
 '(font-lock-doc-face ((t (:inherit (font-lock-string-face)))))
 '(font-lock-function-name-face ((t (:slant italic :foreground "MediumBlue"))))
 '(font-lock-keyword-face ((t (:weight bold :foreground "dark magenta"))))
 '(font-lock-negation-char-face ((t nil)))
 '(font-lock-preprocessor-face ((t (:inherit (font-lock-builtin-face)))))
 '(font-lock-regexp-grouping-backslash ((t (:inherit (bold)))))
 '(font-lock-regexp-grouping-construct ((t (:inherit (bold)))))
 '(font-lock-string-face ((t (:foreground "RoyalBlue3"))))
 '(font-lock-type-face ((t (:foreground "purple4"))))
 '(font-lock-variable-name-face ((t (:slant italic :foreground "blue"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "Red"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:foreground "purple4" :underline t))))
 '(link-visited ((t (:foreground "violet" :inherit (link)))))
 '(fringe ((t (:background "gray87"))))
 '(header-line ((t (:box nil :foreground "grey90" :background "grey20" :inherit (mode-line)))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:inverse-video nil :foreground "gray60" :background "black"))))
 '(mode-line-buffer-id ((t (:foreground "blue4" :background "Gray75" :inherit (sml/filename)))))
 '(mode-line-emphasis ((t (:weight bold))))
 '(mode-line-highlight ((((class color) (min-colors 88)) (:box (:line-width 2 :color "grey40" :style released-button))) (t (:inherit (highlight)))))
 '(mode-line-inactive ((t (:inverse-video nil :foreground "gray60" :background "#404045"))))
 '(isearch ((t (:foreground "brown4" :background "palevioletred2"))))
 '(isearch-fail ((t (:background "red4"))))
 '(lazy-highlight ((t (:background "paleturquoise4"))))
 '(match ((t (:background "RoyalBlue3"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'custom-tr-eclipse)
